version: '3'

services:
  nginx:
    image: codershisho/nginx:1.25.0
    container_name: nginx-the-costume
    tty: true
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - node
  
  node:
    image: codershisho/node:18.18.0-alpine
    container_name: node-the-costume
    tty: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - 3000:3000
      - 24678:24678 # HMR用のポートを追加
      - 5555:5555 # Prismaのポートを追加
    volumes:
      - .:/var/www
    stdin_open: true
    restart: always
      